FROM node:22-bookworm-slim

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends openssl \
  && rm -rf /var/lib/apt/lists/* \
  && corepack enable \
  && corepack install --global pnpm@10.31.0
WORKDIR /app

ENV DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mextdir?schema=public

COPY . .
RUN pnpm install --frozen-lockfile --ignore-scripts
RUN pnpm prepare

EXPOSE 3000

CMD ["pnpm", "dev", "--host", "0.0.0.0"]
